version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: ${DOMAIN}
    environment:
      - PUID=1000
      - PGID=1000
      - VIRTUAL_HOST=${DOMAIN}
      - VIRTUAL_PORT=8384
      - LETSENCRYPT_HOST=${DOMAIN}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${FILES}:/var/syncthing
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
    sysctls:
      - net.core.rmem_max=2097152
    restart: unless-stopped

networks:
  default:
    external:
      name: ${NETWORK}
